

deployment:
  tasks:
    - export DEPLOYMENT_SOURCE=/home/carlamai/project
    - export DEPLOYMENT_TARGET=/home/carlamai/public_html
    - echo "Building Angular project..."
    - cd $DEPLOYMENT_SOURCE
    - cd carla-maid
    - git checkout main
    - git pull origin main
    - echo "Installing Angular dependencies..."
    - npm install
    - ng build
    - echo "Copying build files to deployment target..."
    - rsync -av --delete $DEPLOYMENT_SOURCE/carla-maid/dist/ $DEPLOYMENT_TARGET/