

deployment:
  tasks:
    - export DEPLOYMENT_SOURCE= ~./home/repositories/carlaMaid/carla-maid/
    - export DEPLOYMENT_TARGET= ~./home/public_html/
    - echo "Building Angular project..."
    - cd $DEPLOYMENT_SOURCE
    - git checkout main
    - git pull origin main
    - echo "Installing Angular dependencies..."
    - npm install
    - ng build
    - echo "Copying build files to deployment target..."
    - rsync -av --delete $DEPLOYMENT_SOURCE/carla-maid/dist/ $DEPLOYMENT_TARGET/