---
deployment:
  tasks:
    # Set environment variables for deployment
    - export DEPLOYMENT_SOURCE=/home/carlamai/repositories/carlaMaid/carla-maid/
    - export DEPLOYMENT_TARGET=/home/carlamai/public_html/

    # Navigate to the source directory
    - echo "Navigating to source directory..."
    - cd $DEPLOYMENT_SOURCE

    # Ensure we are on the main branch
    - echo "Switching to the main branch..."
    - git checkout main

    # Pull the latest changes from the repository
    - echo "Pulling the latest changes..."
    - git pull origin main

    # Install dependencies using npm
    - echo "Installing Angular dependencies..."
    - npm install

    # Build the Angular project for production
    - echo "Building Angular project..."
    - ng build --configuration production --output-path=/home/carlamai/public_html/

    # Deploy the build files to the target directory
    - echo "Deploying build files to the target directory..."
    - rsync -av --delete $DEPLOYMENT_SOURCE/dist/ $DEPLOYMENT_TARGET/

    # Log completion
    - echo "Angular project deployed successfully."
